### ISSUE TITLE
the same output?

### ISSUE THREAD

**Issue by lzzk** [julianser/hed-dlg-truncated#8]
hi, i always have same outputs after run sample.py .
could you show me some hints the reason.
thanks

**Comment by julianser** [comment]
Sample.py works fine for me.

The reason you always get the same outputs may be because the model isn't trained properly. For example, you may not have enough data, or the data distribution may be skewed towards a certain response.

Also, notice that you can sample stochastically by not using beam search,

**Comment by dimeldo** [comment]
@lzzk I have the same problem. Did you solved it?

**Comment by lzzk** [comment]
no. i think  adjusting the hyper-paramers may helps.
